apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gemini1234
  template:
    metadata:
      labels:
        app: gemini1234
    spec:
      containers:
        - name: gemini-container
          image: sarita87/gemini1234:01
          ports:
            - containerPort: 5173
