apiVersion: v1
kind: Service
metadata:
  name: gemini-service
spec:
  type: LoadBalancer
  selector:
    app: gemini1234  # Match the Deployment's label
  ports:
    - port: 80
      targetPort: 5173  # Match containerPort in the Deployment
